### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by alexandre-lejeune** [creme-ml/creme#238]
Hi,
I 've been try to launch your example, with bikes.
Like previous issue I have to change datasets loading line by this one "datasets.fetch_bikes()" but I have been this isssue "AttributeError: module 'urllib' has no attribute 'request'".

Thanks.
Regards
Alexandre

**Comment by MaxHalford** [comment]
Hello @alexandre-lejeune! Just to make sure: are you using Python 2 or 3?

**Comment by alexandre-lejeune** [comment]
Python3 with Anaconda

**Comment by MaxHalford** [comment]
I'm going to need some more detail because I wasn't able to reproduce your bug. I just ran the following commands on my computer and it all worked.

First I installed the latest stable version of `creme`:

```sh
>>> conda create -n creme44 python=3.6 anaconda
>>> source activate creme44
>>> pip install creme
```

And then I ran the first cell of the [bikes notebook](https://creme-ml.github.io/notebooks/bike-sharing-forecasting.html):

```python
from pprint import pprint
from creme import datasets

X_y = datasets.fetch_bikes()

for x, y in X_y:
    pprint(x)
    print(f'Number of available bikes: {y}')
    break
```

This produced:

```
{'clouds': 75,
 'description': 'light rain',
 'humidity': 81,
 'moment': datetime.datetime(2016, 4, 1, 0, 0, 35),
 'pressure': 1017.0,
 'station': 'place-des-carmes',
 'temperature': 6.54,
 'wind': 9.3}
Number of available bikes: 3
```

I'm not sure what's not working on your side :(

**Comment by alexandre-lejeune** [comment]
I uninstalled creme and installed it again
```
Successfully uninstalled creme-0.4.4
PS C:\Users\alejeune\OneDrive - Capgemini\Documents\Work\R_I\branches\DA-Lejeune\Test> pip install creme
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting creme
  Using cached creme-0.4.4-cp37-cp37m-win_amd64.whl (558 kB)
Requirement already satisfied: numpy>=1.16.4 in c:\programdata\anaconda3\lib\site-packages (from creme) (1.16.5)
Requirement already satisfied: scipy>=1.3.0 in c:\users\alejeune\appdata\roaming\python\python37\site-packages (from creme) (1.4.1)
Requirement already satisfied: scikit-learn>=0.21.2 in c:\users\alejeune\appdata\roaming\python\python37\site-packages (from creme) (0.22.1)
Requirement already satisfied: joblib>=0.11 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=0.21.2->creme) (0.13.2)
Installing collected packages: creme
Successfully installed creme-0.4.4
```

To be sure I used your code:
```
from pprint import pprint
from creme import datasets

X_y = datasets.fetch_bikes()

for x, y in X_y:
    pprint(x)
    print(f'Number of available bikes: {y}')
    break
```
And I have it:
```
PS C:\Users\alejeune\OneDrive - Capgemini\Documents\Work\R_I\branches\DA-Lejeune\Test> & C:/ProgramData/Anaconda3/python.exe "c:/Users/alejeune/OneDrive - Capgemini/Documents/Work/R_I/branches/DA-Lejeune/Test/TEST.py"
Traceback (most recent call last):
  File "c:/Users/alejeune/OneDrive - Capgemini/Documents/Work/R_I/branches/DA-Lejeune/Test/TEST.py", line 4, in <module>
    X_y = datasets.fetch_bikes()
  File "C:\ProgramData\Anaconda3\lib\site-packages\creme\datasets\__init__.py", line 108, in fetch_bikes
    data_dir_path = download_dataset(name, url, data_home, archive_type='zip', silent=silent)
  File "C:\ProgramData\Anaconda3\lib\site-packages\creme\datasets\__init__.py", line 60, in download_dataset
    with urllib.request.urlopen(url) as r, open(data_dir_path, 'wb') as f:
AttributeError: module 'urllib' has no attribute 'request'
PS C:\Users\alejeune\OneDrive - Capgemini\Documents\Work\R_I\branches\DA-Lejeune\Test>
```
I'm surprise because if I go on the concerned file, at the right line, I can see the argument with the auto-completion.
![image](https://user-images.githubusercontent.com/49685767/74744730-0659a680-5263-11ea-8c46-1a2c265dea98.png)

**Comment by AdilZouitine** [comment]
Hi I tried to reproduce the issue on Python 3.6 with Windows 10 and Linux.
 I couldn't reproduce the result (I also followed the same procedure as max).

**Comment by MaxHalford** [comment]
Just tried again with Python 3.7 and it's also working for me. This could be a Windows issue, but I'd be surprised.

**Comment by alexandre-lejeune** [comment]
Yes, since 15h yesterday I update anaconda and all include packages. I'm sure it's that.

**Comment by Cyxo** [comment]
I've just installed creme on Ubuntu 19 with python 3.7 and I'm getting the same error:
`Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from creme import datasets
>>> X_y = datasets.fetch_electricity()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cyxo/.local/lib/python3.7/site-packages/creme/datasets/__init__.py", line 158, in fetch_electricity
    data_dir_path = download_dataset(name, url, data_home, archive_type='zip', silent=silent)
  File "/home/cyxo/.local/lib/python3.7/site-packages/creme/datasets/__init__.py", line 60, in download_dataset
    with urllib.request.urlopen(url) as r, open(data_dir_path, 'wb') as f:
AttributeError: module 'urllib' has no attribute 'request'
>>> import urllib
>>> urllib.request.urlopen
<function urlopen at 0x7fefec7747a0>`
I see that urllib.request does exist, so idk why there's this error. No Python3 are available right now on Ubuntu, and I'm not using Anaconda

**Comment by alexandre-lejeune** [comment]
I uninstalled and install anaconda too. But still same error. 
I've installed new environment like @MaxHalford suggest, but always same error. 
Really surprising

**Comment by VaysseRobin** [comment]
Hi ! What is your version of urllib ? (You can find it with `conda list urllib` command)

**Comment by alexandre-lejeune** [comment]
```
PS C:\Users\alejeune\OneDrive - Capgemini\Documents\Work\R_I\branches\DA-Lejeune\Test> conda list urllib
# packages in environment at C:\Users\alejeune\.conda\envs\creme44:
#
# Name                    Version                   Build  Channel
urllib3                   1.25.8                   py37_0
```

**Comment by VaysseRobin** [comment]
Please try using an older version of urllib with `conda install urllib3=1.24.2` to check if the problem comes from it.

**Comment by alexandre-lejeune** [comment]
Done, same issue. :(

**Comment by VaysseRobin** [comment]
Hum, that's really weird, I have no idea what to do, I can not reproduce the error :(

**Comment by MaxHalford** [comment]
Okay I guess we're going to have to be more specific. Can you print our your *exact* Python version with `python --version` and give us the output of `pip freeze`.

Just for safety I'm going to change the import of `urllib.request` to `from urllib import request` in future releases. Actually we could use the `requests` package instead.

**Comment by alexandre-lejeune** [comment]
My Python version:
```
PS C:\Users\alejeune\OneDrive - Capgemini\Documents\Work\R_I\branches\DA-Lejeune\Test> python --version
Python 3.7.6

```
And pip freeze result: 
```
PS C:\Users\alejeune\OneDrive - Capgemini\Documents\Work\R_I\branches\DA-Lejeune\Test> pip freeze
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-project==0.8.3
asn1crypto==1.3.0
astroid==2.3.3
astropy==4.0
atomicwrites==1.3.0
attrs==19.3.0
Babel==2.8.0
backcall==0.1.0
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.8.2
bitarray==1.2.1
bkcharts==0.2
bleach==3.1.0
bokeh==1.4.0
boto==2.49.0
Bottleneck==1.3.1
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
Click==7.0
cloudpickle==1.3.0
clyent==1.2.2
colorama==0.4.3
comtypes==1.1.7
contextlib2==0.6.0.post1
creme==0.4.4
cryptography==2.8
cycler==0.10.0
Cython==0.29.15
cytoolz==0.10.1
dask==2.10.1
decorator==4.4.1
defusedxml==0.6.0
distributed==2.10.0
docutils==0.16
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
Flask==1.1.1
fsspec==0.6.2
gevent==1.4.0
glob2==0.7
greenlet==0.4.15
h5py==2.10.0
HeapDict==1.0.1
html5lib==1.0.1
hypothesis==5.5.4
idna==2.8
imageio==2.6.1
imagesize==1.2.0
importlib-metadata==1.5.0
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.16.0
Jinja2==2.11.1
joblib==0.14.1
json5==0.9.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
jupyterlab==1.2.6
jupyterlab-server==1.0.6
keyring==21.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
libarchive-c==2.8
llvmlite==0.31.0
locket==0.2.0
lxml==4.5.0
MarkupSafe==1.1.1
matplotlib==3.1.2
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mock==4.0.1
more-itertools==8.2.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
nltk==3.4.5
nose==1.3.7
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy==1.18.1
numpydoc==0.9.2
olefile==0.46
opencv-contrib-python==4.1.2.30
openpyxl==3.0.3
packaging==20.1
pandas==1.0.1
pandocfilters==1.4.2
parso==0.6.1
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
patsy==0.5.1
pep8==1.7.1
pickleshare==0.7.5
Pillow==7.0.0
pkginfo==1.5.0.1
pluggy==0.13.1
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==3.0.3
psutil==5.6.7
py==1.8.1
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.5
pyflakes==2.1.1
Pygments==2.5.2
pylint==2.4.4
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.6
pyreadline==2.1
pyrsistent==0.15.7
PySocks==1.7.1
pytest==5.3.5
pytest-arraydiff==0.3
pytest-astropy==0.8.0
pytest-astropy-header==0.1.2
pytest-doctestplus==0.5.0
pytest-openfiles==0.4.0
pytest-remotedata==0.3.2
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
pywin32==227
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==5.3
pyzmq==18.1.1
QtAwesome==0.6.1
qtconsole==4.6.0
QtPy==1.9.0
requests==2.22.0
rope==0.16.0
ruamel-yaml==0.15.87
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.10.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.14.0
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.9.5
Sphinx==2.4.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.2.0
spyder==3.3.6
spyder-kernels==0.5.2
SQLAlchemy==1.3.13
statsmodels==0.11.0
sympy==1.5.1
tables==3.6.1
tblib==1.6.0
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.3
tqdm==4.42.1
traitlets==4.3.3
unicodecsv==0.14.1
urllib3==1.25.8
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.0
widgetsnbextension==3.5.1
win-inet-pton==1.1.0
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.11.2
xlrd==1.2.0
XlsxWriter==1.2.7
xlwings==0.17.1
xlwt==1.3.0
zict==1.0.0
zipp==2.2.0
```

**Comment by alexandre-lejeune** [comment]
OK, I've changed import in` __init__.py `of urllib:

```
#import urllib
from urllib import request
```

And his usage:
```
#with urllib.request.urlopen(url) as r, open(data_dir_path, 'wb') as f:
with request.urlopen(url) as r, open(data_dir_path, 'wb') as f:
```

And it works  👍 .
