### ISSUE TITLE
TypeError: 'types' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by zubairahmed-ai** [creme-ml/creme#300]
Hi

I am using the latest version 0.5.1 of `creme` but I using [this blog post](https://www.pyimagesearch.com/2019/06/17/online-incremental-learning-with-keras-and-creme/) I am getting the following error using `stream.iter_csv` function

```
File "train_incremental.py", line 44, in <module>
    for (i, (X, y)) in enumerate(dataset):
  File "/home/pyimagesearch/.virtualenvs/dl4cv/lib/python3.6/site-packages/creme/stream/csv.py", line 97, in iter_csv
    **kwargs
  File "/home/pyimagesearch/.virtualenvs/dl4cv/lib/python3.6/site-packages/creme/stream/csv.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.6/csv.py", line 87, in __init__
    self.reader = reader(f, dialect, *args, **kwds)
TypeError: 'types' is an invalid keyword argument for this function
```

I tried using the `dict()` function like below as [shown here](https://creme-ml.github.io/content/generated/creme.stream.iter_csv.html#creme.stream.iter_csv) but it doesn't work either and gives the same error as above

```
types["class"] = int
params=dict(
   types=types
)
```

**Comment by MaxHalford** [comment]
Hey there. That blog post uses an older version of creme. We're still relatively young (creme has existed for 18 months) so sometimes the API changes. In your case, the `types` argument has been renamed to `converters`.

**Comment by zubairahmed-ai** [comment]
Ok that works, thanks for responding @MaxHalford but I ran into another issue now

```
Traceback (most recent call last):
  File "train_incremental.py", line 45, in <module>
    preds = model.predict_one(X)
  File "/home/pyimagesearch/.virtualenvs/dl4cv/lib/python3.6/site-packages/creme/compose/pipeline.py", line 286, in predict_one
    return self.final_estimator.predict_one(x=x)
AttributeError: 'list' object has no attribute 'predict_one'

```

**Comment by MaxHalford** [comment]
Not sure but you're probably using a pipeline. Therefore when you initialize the pipeline you'll have to remove the brackets that were necessary in previous versions.
